# Default values for certificate-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
modules:
  manager:
    enabled: true

cert-manager:
  nameOverride: certificate-manager
  installCRDs: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  webhook:
    podAnnotations:
      sidecar.istio.io/inject: "false"
  cainjector:
    podAnnotations:
      sidecar.istio.io/inject: "false"
  extraArgs:
  - --cluster-resource-namespace=istio-system