apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oathkeeper.fullname" . }}-rules
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
data:
  "access-rules.json": |
    [
      {
        "id":"httpbin-read",
        "description":"",
        "match":{
          "methods":["GET"],
          "url":"<http|https>://httpbin-proxy.kyma.local/<.*>"
        },
        "authenticators":[
          {
            "handler":"oauth2_introspection",
            "config":{
              "required_scope": ["read"]
            }
          }
        ],
        "authorizer":{
          "handler":"allow"
        },
        "mutator":{
          "handler":"noop"
        },
        "upstream":{
          "preserve_host":false,
          "strip_path":"",
          "url":"http://httpbin.default.svc.cluster.local:8000"
        }
      },
      {
        "id":"httpbin-write",
        "description":"",
        "match":{
          "methods":["POST"],
          "url":"<http|https>://httpbin-proxy.kyma.local/post"
        },
        "authenticators":[
          {
            "handler":"oauth2_introspection",
            "config":{
              "required_scope": ["write"]
            }
          }
        ],
        "authorizer":{
          "handler":"allow"
        },
        "mutator":{
          "handler":"noop"
        },
        "upstream":{
          "preserve_host":false,
          "strip_path":"",
          "url":"http://httpbin.default.svc.cluster.local:8000"
        }
      }
    ]

