apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "legacy.fullname" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kyma-installer
  name: {{ include "legacy.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "legacy.fullname" . }}
  namespace: kyma-installer
subjects:
  - kind: ServiceAccount
    name: {{ include "legacy.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "legacy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
