---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  duration: 720h
  renewBefore: 10m
  keySize: 4096
  organization: # For debugging purposes
  - kyma
  commonName: {{ .Values.global.domainName }}
  dnsNames:
  - "*.{{ .Values.global.domainName }}"
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: own-domain
    kind: ClusterIssuer
    group: cert-manager.io