---
apiVersion: v1
data:
  "tls.key": {{ .Values.global.ingress.tlsKey }}
  "tls.crt": {{ .Values.global.ingress.tlsCrt }}
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
