{{- if eq .Values.global.certificates.type "xip" }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: {{ template "name" . }}-init
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - list
    resourceNames:
      - kyma-ca-key-pair
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name" . }}-init
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "name" . }}-init
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
