---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kyma-gateway-certs
  namespace: $ROOTCA_SECRET_NAMESPACE
spec:
  duration: 720h
  renewBefore: 10m
  keySize: 4096
  organization:
  - kyma
  commonName: $XIP_DOMAIN
  dnsNames:
  - "*.$XIP_DOMAIN"
  secretName: kyma-gateway-certs
  issuerRef:
    name: kyma-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io