{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-pushgateway.serviceAccountName" . }}
  labels:
    {{ include "prometheus-pushgateway.labels" . | indent 4 }}
{{ template "prometheus-pushgateway.defaultLabels" merge (dict "extraLabels" .Values.serviceAccountLabels) .  }}
{{- end -}}
