apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "delete-helm-release.fullname" . }}-xip-patch-job
  namespace: kyma-installer
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook: "post-upgrade"
    helm.sh/hook-weight: "10"
  labels:
    chart: {{ template "delete-helm-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  activeDeadlineSeconds: 30
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: job
          command:
            - bash
            - "-c"
            - |
{{.Files.Get "files/delete-release.sh" | printf "%s" | indent 16}}
          image: {{ .Values.deleteJob.image.repository }}:{{ .Values.deleteJob.image.tag }}
          imagePullPolicy: {{ .Values.deleteJob.image.pullPolicy }}
          env:
          - name: RELEASE_NAME
            value: "xip-patch"
          - name: RELEASE_NAMESPACE
            value: "kyma-installer"
          # Generic retry in the script to overcome random network failures.
          - name: RETRIES_ON_COMMAND_FAILURE
            value: "2"
      restartPolicy: Never
      serviceAccountName: kyma-installer

