---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rule-controller-account
  namespace:  {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rule-controller-role
  # namespace:  {{ .Release.Namespace }}
rules:
  - apiGroups: ["oathkeeper.ory.sh"]
    resources: ["rules"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
    # TODO, fix controller call from all namespaces to single namespace
    # resourceNames:
    #   - {{ .Values.configMapName | default "ory-oathkeeper-rules" }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rule-controller-role-binding
  namespace:  {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: rule-controller-account # Service account assigned to the rule-controller pod.
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rule-controller-role
