jobs:
  crdsInConfigMap: 20
  image:
    repository: demonsthere/kyma-crds
    tag: "v3"
  installer:
    namespace: kyma-installer

global:
  isLocalEnv: false
  disableLegacyConnectivity: false

containerRegistry:
  path: eu.gcr.io/kyma-project

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "978664da"
  # Image pull policy
  pullPolicy: IfNotPresent
