jobs:
  crdsInConfigMap: 20
  image:
    repository: eu.gcr.io/kyma-project/incubator/develop/k8s-tools
    tag: "20201023-5de446cf"
  installer:
    namespace: kyma-installer

global:
  isLocalEnv: false
  disableLegacyConnectivity: false
  delete-helm-release:
    enabled: true
  # Use this mechanism to exclude a CRD from being installed if you don't need it.
  # Provide a string with a comma-separated list of CRD file names (without path!) that will be excluded from installation.
  # The files are located in the ./files directory of this chart.
  skipCrds: ""

containerRegistry:
  path: eu.gcr.io/kyma-project

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "978664da"
  # Image pull policy
  pullPolicy: IfNotPresent

limitRange:
  max:
    memory: 4Gi
  default:
    memory: 96Mi
  defaultRequest:
    memory: 32Mi
