service:
  port: 8000
  name: iam-kubeconfig-service

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi
global:
  tlsCrt: "cGxhY2Vob2xkZXI="
  tlsKey: "cGxhY2Vob2xkZXI="
  isLocalEnv: false
  istio:
    gateway:
      name: kyma-gateway
  containerRegistry:
    path: eu.gcr.io/kyma-project
  iam_kubeconfig_service:
    dir:
    version: 1af8f7a8
