---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}-copy
  namespace: "{{ .Values.overrides.namespace }}"
  labels:
    installer: overrides
    kyma-project.io/installation: ""
data:
  {{- if or (eq .Values.global.isLocalEnv true) (eq .Values.global.certificates.type "legacy") }}
  global.certificates.type: "legacy"
  {{- else if eq .Values.global.certificates.type "gardener" }}
  global.certificates.type: "gardener"
  {{- else if eq .Values.global.certificates.type "xip" }}
  global.certificates.type: "xip"
  {{- else if eq .Values.global.certificates.type "user-provided" }}
  global.certificates.type: "user-provided"
  {{- else }}
  global.certificates.type: "detect"
  {{- end }}
  {{- if .Values.global.domainName }}
  global.domainName: "{{ .Values.global.domainName }}"
  global.ingress.domainName: "{{ .Values.global.domainName }}"
  {{- end }}
  {{- if .Values.global.loadBalancerIP }}
  global.loadBalancerIP: "{{ .Values.global.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.global.minikubeIP }}
  global.minikubeIP: "{{ .Values.global.minikubeIP }}"
  {{- end }}
  {{- if .Values.global.tlsCrt }}
  global.tlsCrt: "{{ .Values.global.tlsCrt }}"
  {{- end }}
  {{- if .Values.global.tlsKey }}
  global.tlsKey: "{{ .Values.global.tlsKey }}"
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificates-overrides
  namespace: "{{ .Values.overrides.namespace }}"
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: certificates
data:
  modules.manager.enabled: "{{ .Values.global.certificates.manager.enabled }}"
  {{- if eq .Values.global.certificates.type "xip" }}
  modules.xip.enabled: "true"
  {{- end }}
  {{- if eq .Values.global.certificates.type "gardener" }}
  modules.gardener.enabled: "true"
  {{- end }}
  {{- if eq .Values.global.certificates.type "legacy" }}
  modules.legacy.enabled: "true"
  {{- end }}
  {{- if eq .Values.global.certificates.type "user-provided" }}
  modules.user-provided.enabled: "true"
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-overrides
  namespace: "{{ .Values.overrides.namespace }}"
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: certificate-manager
data:
  modules.manager.enabled: "{{ .Values.global.certificates.manager.enabled }}"