apiVersion: rafter.kyma-project.io/v1beta1
kind: ClusterAssetGroup
metadata:
  labels:
    rafter.kyma-project.io/view-context: docs-ui
    rafter.kyma-project.io/group-name: components
    rafter.kyma-project.io/order: "1"
  name: security-v2
spec:
  displayName: "Security v2"
  description: "Overall documentation for Security"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/{{ .Values.global.kymaOrgName }}/kyma/archive/{{ .Values.global.docs.clusterAssetGroupsVersion }}.zip
      filter: /docs/security-v2/