apiVersion: v2
name: prometheus-pushgateway
description: A Helm chart for prometheus pushgateway
type: application
version: 1.4.0
appVersion: "1.2.0"
home: https://github.com/prometheus/pushgateway
sources:
- https://github.com/prometheus/pushgateway
keywords:
- pushgateway
- prometheus
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: christian.staude@staffbase.com
  name: cstaud
