{{ if eq .Values.global.certificates.type "xip" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "name" . }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      - get
      - list
    resourceNames:
      - apiserver-proxy-ssl
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "name" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: {{ template "name" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - list
    resourceNames:
      - kyma-ca-key-pair
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-system
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}