---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "0"
  name: {{ .Chart.Name }}-restart-job
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
  name: {{ .Chart.Name }}-restart-job
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-restart-job
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-restart-job
    namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
  name: {{ .Chart.Name }}-restart-job
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list"]
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Chart.Name }}-restart-job
  namespace: istio-system
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      name: {{ .Chart.Name }}-restart-job
      namespace: istio-system
      annotations:
        sidecar.istio.io/inject: “false”
    spec:
      serviceAccountName: {{ .Chart.Name }}-restart-job
      restartPolicy: OnFailure
      containers:
        - name: restart
          image: bitnami/kubectl:1.15
          command:
            - bash
            - -c
            - |
              kubectl delete pod -n istio-system -l app=istio-ingressgateway --wait=true
