---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    installer: overrides
    kyma-project.io/installation: ""
data:
  {{- if .Values.global.isLocalEnv }}
  global.environment.type: "local"
  global.environment.ownDomain: "true"
  {{- else if .Values.global.isOwnDomain }}
  global.environment.type: "own-domain"
  global.environment.own-domain: "true"
  {{- else if .Values.global.isGardenerEnv }}
  global.environment.type: "gardener"
  global.environment.gardener: "true"
  {{- else if .Values.global.isXipEnv }}
  global.environment.type: "xip"
  global.environment.xip: "true"
  {{- end }}
  {{- if .Values.global.domainName }}
  global.ingress.domainName: "{{ .Values.global.domainName }}"
  {{- end }}
  {{- if .Values.global.loadBalancerIP }}
  global.loadBalancerIP: "{{ .Values.global.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.global.minikubeIP }}
  global.minikubeIP: "{{ .Values.global.minikubeIP }}"
  {{- end }}
  {{- if .Values.global.minikubeIP }}
  global.ingress.tlsCrt: "{{ .Values.global.tlsCrt }}"
  {{- end }}
  {{- if .Values.global.minikubeIP }}
  global.ingress.tlsKey: "{{ .Values.global.tlsKey }}"
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificates-overrides
  namespace: {{ .Release.Namespace }}
  labels:
    installer: overrides
    kyma-project.io/installation: ""
    component: certificates
data:
  modules.manager.enabled: "true"
  modules.xip.enabled: "false"
  modules.gardener.enabled: "false"
  modules.ownDomain.enabled: "true"
