---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-info.fullname" . }}-gardener
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cluster-info.fullname" . }}-gardener
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: 
    - get
    - list
    - patch
  resourceNames: 
    - {{ .Values.configMapName }}
    - certificates-overrides
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-info.fullname" . }}-gardener
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-info.fullname" . }}-gardener
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cluster-info.fullname" . }}-gardener
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.gardener.shootInfo.namespace }}
  name: {{ include "cluster-info.fullname" . }}-gardener
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: 
    - get
    - list
  resourceNames: ["{{ .Values.gardener.shootInfo.name }}"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-info.fullname" . }}-gardener
  namespace: {{ .Values.gardener.shootInfo.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-info.fullname" . }}-gardener
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cluster-info.fullname" . }}-gardener
  apiGroup: rbac.authorization.k8s.io
