---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xip.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "xip.fullname" . }}-ingress
rules:
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs:
    - get
    - list
    - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "xip.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "xip.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "xip.fullname" . }}-ingress
  apiGroup: rbac.authorization.k8s.io
