---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-crd-install
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "10"
spec:
  activeDeadlineSeconds: 180
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Release.Name }}-crd-install
      restartPolicy: OnFailure
      containers:
      - name: {{ .Release.Name }}-install-crds
        image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag }}"
        command:
        - /bin/sh
        - -c
        args:
        - |
          set -e
          kubectl apply -f /etc/crds
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m