{{ $files := .Files.Glob "files/**.yaml" }}
{{ $fileLen := len $files }}
{{ $configMapLen := int (add1 (div $fileLen .Values.jobs.crdsInConfigMap)) }}

{{ $currentScope := . }}
{{ $skipCrds := regexSplit "," .Values.global.skipCrds -1 }} #split words between "," into a list
{{ $skipCrdList := list }} #Iterate over the values to trim whitespaces
{{ range $_, $toSkip := $skipCrds }}
{{ $skipCrdList = append $skipCrdList (trim $toSkip) }}
{{ end }}

{{ $filePaths := list }}
{{ range $path, $_ := $files }}
{{ if (not (has (base $path) $skipCrdList)) }}
{{ $filePaths = append $filePaths (base $path) }}
{{ end }}
{{ end }}

{{ range $idx, $_ := until $configMapLen }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- with $currentScope }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-crd-{{ $idx }}
  {{- end }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ range $pathIdx, $path := $filePaths }}
  {{- with $currentScope }}
  {{ if eq $idx (mod $pathIdx $configMapLen) }}
  {{ base $path }}: |-
{{ .Files.Get (printf "files/%s" $path) | printf "%s" | indent 4 }}
  {{ end }}
  {{- end }}
{{ end }}
---
{{ end }}
