{{- if .Values.loki.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  mtls:
    mode: "PERMISSIVE"
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  jwtRules:
  - issuer: https://dex.{{ .Values.global.ingress.domainName }}
    jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  rules:
   - from:
     - source:
         requestPrincipals: ["*"]
   - to:
     - operation:
         paths:
         - "/health"
         - "/ready"
         - "/metrics"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: logging-fluentbit
  namespace: kyma-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  rules:
  - from:
    - source:
        principals:
        #TODO: "logging-fluent-bit" sa name is defined by fluentbit subchart. Find a proper way to refer to this name, instead of hard-coding it.
        - cluster.local/ns/{{ .Release.Namespace }}/sa/logging-fluent-bit
{{- end }}
