{{- if .Values.loki.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  mtls:
    mode: "PERMISSIVE"
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  jwtRules:
  - issuer: https://dex.{{ .Values.global.ingress.domainName }}
    jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
  rules:
   - from:
     - source:
         requestPrincipals: ["*"]
   - to:
     - operation:
         paths:
         - "/health"
         - "/ready"
         - "/metrics"
{{- end }}
