{{- $generateCertForXIPDomain := (eq .Values.global.certificates.type "xip") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}

{{- if $generateCertForXIPDomain }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.caSecret.namespace }}
  name: {{ template "name" . }}-init
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - list
    resourceNames:
      - {{ .Values.caSecret.name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name" . }}-init
  namespace: {{ .Values.caSecret.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "name" . }}-init
  apiGroup: rbac.authorization.k8s.io
{{- end }}
