---
# Secure port service
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-ssl
  namespace: {{ .Release.Namespace }}
{{- if eq .Values.global.certificates.type "gardener" }}
  annotations:
    cert.gardener.cloud/secretname: {{ template "name" . }}-tls-cert
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ printf "apiserver.%s" .Values.global.ingress.domainName }}
{{- end }}
spec:
  {{- if hasKey .Values.global "minikubeIP" }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.port.secure }}
  selector:
    app: {{ template "name" . }}
---
# Insecure port service
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.port.insecure }}
    protocol: TCP
    targetPort: {{ .Values.port.insecure }}
  selector:
    app: {{ template "name" . }}
---
# Dedicated Service for metrics endpoint
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-metrics
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.port.metrics }}
  selector:
    app: {{ template "name" . }}
