{{- $Namespace := tpl .Values.tests.config.namespace.dynamicNamespace $ -}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-test-admin-binding
  namespace: {{ .Values.tests.config.namespace.testNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-admin
subjects:
- kind: User
  name: admin@kyma.cx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-test-ro-user-binding
  namespace: {{ .Values.tests.config.namespace.testNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-view
subjects:
- kind: User
  name: read-only-user@kyma.cx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-test-namespace-developer
  namespace: {{ $Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-developer
subjects:
- kind: User
  name: developer@kyma.cx
  apiGroup: rbac.authorization.k8s.io
