---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  global.ory.hydra.persistence.enabled: "true"
  global.ory.hydra.persistence.postgresql.enabled: "true"
  global.ory.hydra.persistence.gcloud.enabled: "false"
  hydra.hydra.autoMigrate: "true"
