---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  global.ory.hydra.persistence.enabled: "true"
  global.ory.hydra.persistence.postgresql.enabled: "false"
  global.ory.hydra.persistence.gcloud.enabled: "true"
  hydra.hydra.autoMigrate: "true"
  # gcloud sql proxy settings
  gcloud-sqlproxy.cloudsql.instance.instanceName: "myinstance"
  gcloud-sqlproxy.cloudsql.instance.project: "my-gcloud-project"
  gcloud-sqlproxy.cloudsql.instance.region: "europe-west4"
  gcloud-sqlproxy.cloudsql.instance.port: "5432"
  gcloud-sqlproxy.existingSecret: "ory-gcloud-sa"
  gcloud-sqlproxy.existingSecretKey: "sa.json"
  # gcloud db settings
  global.ory.hydra.persistence.user: "hydra"
  global.ory.hydra.persistence.secretName: "ory-gcloud-sa"
  global.ory.hydra.persistence.secretKey: "password"
  global.ory.hydra.persistence.dbUrl: "ory-gcloud-sqlproxy.kyma-system.svc.cluster.local:5432"
  global.ory.hydra.persistence.dbName: "db4hydra"
  global.ory.hydra.persistence.dbType: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    component: ory
  name: ory-gcloud-sa
  namespace: kyma-system
type: Opaque
data:
  # sa.json: ServiceAccount json file from GCloud, base64 encoded
  sa.json: ""
  # password: password base64 encdoded
  password: cGFzc3dvcmQK