---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  # hydra settings
  global.ory.hydra.persistence.enabled: "true"
  global.ory.hydra.persistence.gcloud.enabled: "true"
  hydra.hydra.autoMigrate: "true"
  # gcloud sql proxy settings
  gcloud-sqlproxy.cloudsql.instance.instanceName: "myinstance"
  gcloud-sqlproxy.cloudsql.instance.project: "my-gcloud-project"
  gcloud-sqlproxy.cloudsql.instance.region: "europe-west4"
  gcloud-sqlproxy.cloudsql.instance.port: "5432"
  # gcloud db settings
  global.ory.hydra.persistence.user: "hydra"
  global.ory.hydra.persistence.dbUrl: "ory-gcloud-sqlproxy.kyma-system.svc.cluster.local"
  global.ory.hydra.persistence.dbName: "db4hydra"
  global.ory.hydra.persistence.dbType: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
  name: ory-overrides-secrets
  namespace: kyma-installer
type: Opaque
data:
  # hydra settings
  # hydra.hydra.config.secrets.system: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.system: Y3VzdG9tIHNpZ25pbmcga2V5LCBiYXNlNjQgZW5jZG9kZWQ=
  # hydra.hydra.config.secrets.cookie: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.cookie: Y3VzdG9tIHNpZ25pbmcga2V5LCBiYXNlNjQgZW5jZG9kZWQ=
  # db settings
  global.ory.hydra.persistence.gcloud.saJson: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic2FwLXNlLWN4LWt5bWEtZ29hdCIsCiAgInByaXZhdGVfa2V5X2lkIjogImI3M2IyNTZmNDg5NDliODJlN2JmMTM3OGYzZDUxMTkzM2UxNDE3ZWQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGxJcFhUUTBha0phNUFcbkxjTTNPYUpQRTNPR1ZLRFNFK08wRzYyWTY2TmhQRDlPNUo5ZFo2YUNpUWNJcG1mQ2RiM3A4bHYxdVRWRjByQ1pcblp3Q3JMQ0RqVGF2VnhMM1RNTGN0RFJWQmNPQXJOM1Bldm41bFRiWlpzcGdaai81TXZJWkFxK0N0QVpLVXdIeXlcbjFNdEJMZkdMZ3Q3RzZna2JVb2RXemJKenB6cERIb2NNYnhueVh5M2cxU2UyT0x5bXYwYkpzZUMvRTA3bzB5WWZcbjhDQTNIQXk0cDg4eTNqNURWai9CaWRKVkFyMTlITmNuU2xxZm1rVHY1aThqa0dNVm83MFhaNTdhenp4dVBUZUFcbnBaUXp1NWVWUC9FVkMzN01lYVh0aXE2SWZDeHJzYzZ4cEZXQkp4MjRzN3Vicld0eG5RMEMvTEVDNnU0VU1WK3BcbkEvYitOK3ZOQWdNQkFBRUNnZ0VBQmZNUm5DeFpXalpzUVlNRUF2RnBLSHA0ZThWdUdPWlJUdXpsRGdmQzlKUmhcbmp4cUZQM2RMTGRxQnB6K0MzdHdRYy94S0FsQlpIMjRBRGVEM0lIcXQyVU84QnM5QlNvbUU4cjR0NDNGd2hmbG9cbjljdFJIQythQzRHRlROZElvcjl4RVBRbGlrM0owT09mN3BqSWlrY015RExtdHBncHZRbUxOV2dlam1nMDJCSHNcbmx5VTU0MHJFditpbVRUQ2tWT0puRDlySWtnSmJ2RUFFTWphWGRXcGw4dEUwc2ljVGZ0VktsQ3ArWTV3dExLcHpcbk9sZE9HVEx4TjNTZWRxWllaUGhqMmttckovRm82SDVvREtoSXAxMFJ1QjA4dkNoTUNka0FrMjlOdTJUVFFHNjdcbnYzWHczWEFDQ2Y2NWNsVUFxbDA4QXlVRlNlUS83VGJULzJIR0JYeGlvUUtCZ1FEK3lxYnpnMGNHREd0RFdKYkpcbmptMDNXRGd6RWljU1ZKeU05T2s2ZXQrT21aY0M1YTAwWW5MYlhQWW9aRXBlOXdxUDFnUXRMUEk2a0c5MFNRdnlcbm1YOGcyRkV0NURreTNldlkzbTlrTTY4WmpoZ0tod0lRWnAzRlVaam5QZU5DaHBOT1h4MjZZTnNXbklnejVNZjFcbnZpWDNWekVzc0dpMlpkMnB4RzFtTU1nc1ZRS0JnUURtT01oeUxacWhyMlV5WGtzRVJEQmVvdjVhZG5sV25TMUJcbkJvQno1cFR5ZXR5RWxuQzZXKzVESUhkbDB6Ky9pQlZuVjdhS2Nka1NZdit4ZkY3RnZNUEF6VWFxZlhKQlBjZGlcblNPWm9OOERva0FOcWxScE5JUE51ejJuT0cxTkRSS2E1S09hSnhMOXh4YWJzNXdVYVZBejNvRTV2ZVhFbERvdXhcbldSMG1RRnk1bVFLQmdRRFlvQ1BoMWpPRWlQcUpmOEIwRFl2K0NodCtFR2ozeE1oMWI2VDcrNHduQ1o3Qzc5T2JcblBqaTVHUWlRdnZRY1daMjVQUlMvOC83ZW0vNm10NVJZNXZpWFRGTjQyUmxvamhYL2hON2dLckVzNFFxL3FKbXdcbnFBNXJ2VHhySHNzaHZKbHhnSjBkNFV0a3BpR0hQWFJsRXcza2hWVmgwWHExMlZYbENRU2FaYzlMSVFLQmdDYzBcbkZDNGRSZSt5aG5FRlRaRDBhNmd4NlU1T1RtdEphS05pRUEyc2ZrQ3NXMURZcldtT3Jnd1FRMFM3ckdkWkxRdmtcbkM5bVhlWGVBRkRxTkN6Wnc1b1MyY0Fvb1FvU0ptS0pMOTdCWGppb01IQWpTU3lCSE5DenlkUG43L1RtL1B3VFlcbnlpazdyNzRZQWt6bEtpRkpuc3VzS0s4aTV2bUFlSmxDcTR3UCticEJBb0dCQUxyV2EzR3NEUnRwNEhscy9GTFBcbnNHdWFheDZ0b21DSXpKclRKTFUzN2RIb0kvR21ObFQ0U3pEejNwaXdNL2V4aWhYdzRvRnRqbXlKeVBMaUthOUhcbmkzWGx1dVYyUEJvQWV2ZngrYXV5clhTUWtQSTI0TXlBbDlOdDF3Rm1SWGdTSnJFZTIwQXBQVzJOaVFEa1RvSWpcbjNLS2E2WFlaL1E1ak1tMVZLUjlUeGVTZVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInNxbC1wcm94eUBzYXAtc2UtY3gta3ltYS1nb2F0LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwOTcxNzUwODA0NDA2MDM3OTIzNyIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvc3FsLXByb3h5JTQwc2FwLXNlLWN4LWt5bWEtZ29hdC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
  global.ory.hydra.persistence.password: aHlkcmEK
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
  name: ory-overrides-secrets
  namespace: kyma-installer
type: Opaque
data:
  # hydra settings
  # hydra.hydra.config.secrets.system: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.system: Y3VzdG9tIHNpZ25pbmcga2V5LCBiYXNlNjQgZW5jZG9kZWQ=
  # hydra.hydra.config.secrets.cookie: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.cookie: Y3VzdG9tIHNpZ25pbmcga2V5LCBiYXNlNjQgZW5jZG9kZWQ=
  # global.ory.hydra.persistence.gcloud.saJson: ServiceAccount json file from GCloud, base64 encoded
  global.ory.hydra.persistence.gcloud.saJson: ""
  # global.ory.hydra.persistence.password: password, base64 encdoded
  global.ory.hydra.persistence.password: aHlkcmEK
