apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kyma-installer
  name: {{ .Release.Name }}-kyma-installer-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "clusterissuers"]
    verbs: ["get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-kyma-installer-role-binding
  namespace: kyma-installer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-kyma-installer-role
  apiGroup: rbac.authorization.k8s.io
