{{- if and (.Values.enabled) (.Values.serviceMonitor.enabled) }}
apiVersion: authentication.istio.io/v1alpha1
kind: PeerAuthentication
metadata:
  name: {{ template "fluent-bit.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "fluent-bit.matchLabels" . | trim | nindent 6 }}
  mtls:
    mode: "PERMISSIVE"
{{- end }}

